"""Tests for the correlation-robust covariance.

The claim being defended is that ``sigma^2 (J^T J)^-1`` understates the real
scatter of a geometrically fitted parameter when residuals are correlated, and
that the Newey-West sandwich reduces that error.

Two levels of evidence, because they fail for different reasons:

* **Exact.**  For a *linear* model with AR(1) errors the true covariance of the
  estimator is available in closed form,
  ``(X^T X)^-1 X^T Sigma X (X^T X)^-1``, so the sandwich can be judged against
  the truth rather than against another estimate.  No Monte Carlo is needed and
  there is no simulation noise in the target.
* **Integration.**  On a real synthetic drop profile, the covariance must be
  invariant to the order in which the profile points are supplied.  That is
  what the meridian reordering inside ``parameter_covariance`` is for, and
  without it a lag-based estimator measures correlation along the *array*
  instead of along the *drop*.

The measured profile-pipeline numbers (0.89 naive vs 0.95 HAC on i.i.d. noise;
1.93 vs 1.21 on correlated noise, over 60 realisations) are recorded in
``docs/validation/hac-covariance.md``.  They are deliberately NOT asserted here
at tight tolerance: they are Monte Carlo estimates, and pinning them would make
the suite flaky rather than more correct.

Run directly (python tests/test_uncertainty_robust.py) or under pytest.
"""
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src'))

from drop3d.tensiometry import synthesise_pendant_drop, young_laplace_fit  # noqa: E402
from drop3d.uncertainty import (  # noqa: E402
    _hac_sandwich,
    _newey_west_bandwidth,
    parameter_covariance,
)

BO, RADIUS, APEX, N_PTS = 0.30, 150.0, (400.0, 700.0), 70


# ============================================================ exact criterion
def _design(n=150, p=3):
    """A design matrix shaped like a profile Jacobian: smooth, correlated columns."""
    t = np.linspace(-1.0, 1.0, n)
    X = np.column_stack([np.ones(n), t, t ** 2 - 1.0 / 3.0])[:, :p]
    return X


def _ar1_sigma(n, rho, sigma=1.0):
    idx = np.arange(n)
    return sigma ** 2 * rho ** np.abs(idx[:, None] - idx[None, :]) / (1.0 - rho ** 2)


def _exact_ols_cov(X, Sigma):
    """Var(beta_hat) = (X'X)^-1 X' Sigma X (X'X)^-1.  Exact, not an estimate."""
    XtX_inv = np.linalg.inv(X.T @ X)
    return XtX_inv @ (X.T @ Sigma @ X) @ XtX_inv


def _mean_predicted_stds(X, Sigma, n_real=1000, seed=0, coefficient=1, rho=None):
    """Average the naive and HAC standard errors over many error draws.

    Errors are generated by the exact stationary AR(1) recursion rather than
    through ``multivariate_normal``: the latter factorises a dense n x n
    covariance on every draw, which is O(n^3) each and dominated the runtime of
    this file.  The recursion is O(n) per draw and gives the identical
    distribution.
    """
    rng = np.random.default_rng(seed)
    n, p = X.shape
    XtX_inv = np.linalg.inv(X.T @ X)
    dof = n - p
    L = _newey_west_bandwidth(n)

    if rho is None:
        rho = float(Sigma[0, 1] / Sigma[0, 0])
    if rho == 0.0:
        E = rng.normal(0.0, math.sqrt(Sigma[0, 0]), size=(n_real, n))
    else:
        z = rng.normal(0.0, 1.0, size=(n_real, n))
        E = np.empty_like(z)
        E[:, 0] = z[:, 0] / math.sqrt(1.0 - rho ** 2)
        for t in range(1, n):
            E[:, t] = rho * E[:, t - 1] + z[:, t]
        E *= math.sqrt(Sigma[0, 0] * (1.0 - rho ** 2))

    naive, hac = [], []
    for e in E:
        beta = XtX_inv @ (X.T @ e)
        resid = e - X @ beta
        sigma2 = float(resid @ resid) / dof
        naive.append(math.sqrt(sigma2 * XtX_inv[coefficient, coefficient]))
        cov, _ = _hac_sandwich(X, resid, bandwidth=L)
        hac.append(math.sqrt(cov[coefficient, coefficient]))
    return float(np.mean(naive)), float(np.mean(hac)), L


def test_hac_beats_naive_against_the_exact_covariance_under_correlation():
    """The central claim, tested against a closed-form truth."""
    n, rho = 150, 0.8
    X = _design(n)
    Sigma = _ar1_sigma(n, rho)
    exact = math.sqrt(_exact_ols_cov(X, Sigma)[1, 1])

    naive, hac, L = _mean_predicted_stds(X, Sigma)

    err_naive = abs(naive - exact) / exact
    err_hac = abs(hac - exact) / exact
    assert err_hac < err_naive, (
        f'HAC ({hac:.4f}) should be closer to the exact {exact:.4f} than '
        f'naive ({naive:.4f}); errors {err_hac:.1%} vs {err_naive:.1%}')

    # and the naive one must fail in the dangerous direction: too small
    assert naive < exact, f'expected naive to understate; {naive} vs exact {exact}'


def test_hac_degrades_with_correlation_but_still_beats_naive():
    """The measured behaviour on the exact criterion, across rho.

    HAC is uniformly better than naive for any positive correlation, but it is
    NOT a complete fix: its accuracy falls off as rho rises, because the
    automatic Newey-West bandwidth is set by the sample size and does not grow
    with the correlation length.  The measured recovery of the true standard
    error is 95% at rho=0, 80% at 0.5, 56% at 0.8 and 27% at 0.95.

    These bounds are deliberately loose around the measured values: the numbers
    are Monte Carlo estimates, so asserting them tightly would buy flakiness
    rather than correctness.  What is asserted firmly is the *ordering* claim,
    which is the one the estimator selection rests on.
    """
    n = 150
    X = _design(n)

    for rho, lo, hi in ((0.5, 0.65, 0.95), (0.8, 0.45, 0.70)):
        Sigma = _ar1_sigma(n, rho)
        exact = math.sqrt(_exact_ols_cov(X, Sigma)[1, 1])
        naive, hac, _ = _mean_predicted_stds(X, Sigma)
        assert hac < exact, f'rho={rho}: HAC {hac:.4f} should still be low'
        assert naive < hac, f'rho={rho}: naive {naive:.4f} vs hac {hac:.4f}'
        assert lo < hac / exact < hi, (
            f'rho={rho}: HAC recovered {hac / exact:.1%} of the exact standard '
            f'error, outside the measured band [{lo:.0%}, {hi:.0%}]')
        # the naive bar is the catastrophic one
        assert naive / exact < 0.6, (
            f'rho={rho}: expected the naive bar to be badly low, got '
            f'{naive / exact:.1%}')


def test_recovery_gets_worse_as_correlation_grows():
    """Monotone degradation, which is why the code refuses to extrapolate."""
    n = 150
    X = _design(n)
    recovered = []
    for rho in (0.3, 0.6, 0.9):
        Sigma = _ar1_sigma(n, rho)
        exact = math.sqrt(_exact_ols_cov(X, Sigma)[1, 1])
        _, hac, _ = _mean_predicted_stds(X, Sigma)
        recovered.append(hac / exact)
    assert recovered[0] > recovered[1] > recovered[2], recovered


def test_hac_does_not_inflate_independent_errors():
    """The guard on the guard: on i.i.d. errors HAC must not blow the error bar up.

    An estimator that 'fixes' correlation by always inflating would be useless.
    """
    n = 150
    X = _design(n)
    Sigma = np.eye(n)                      # rho = 0
    exact = math.sqrt(_exact_ols_cov(X, Sigma)[1, 1])
    naive, hac, _ = _mean_predicted_stds(X, Sigma)
    assert 0.7 < hac / exact < 1.4, f'hac {hac:.4f} vs exact {exact:.4f}'
    assert 0.7 < naive / exact < 1.4, f'naive {naive:.4f} vs exact {exact:.4f}'
    # on independent errors the two estimators should broadly agree
    assert 0.6 < hac / naive < 1.6, f'hac/naive = {hac / naive:.3f}'


def test_the_sandwich_is_symmetric_positive_definite():
    n = 60
    rng = np.random.default_rng(3)
    X = rng.normal(size=(n, 4))
    e = rng.normal(size=n)
    cov, info = _hac_sandwich(X, e)
    assert cov.shape == (4, 4)
    assert np.allclose(cov, cov.T, atol=1e-14)
    assert np.all(np.linalg.eigvalsh(cov) > -1e-12)
    assert info['bandwidth'] >= 1


def test_bandwidth_grows_with_sample_size_and_is_bounded_by_it():
    assert _newey_west_bandwidth(50) >= 1
    assert _newey_west_bandwidth(100000) > _newey_west_bandwidth(100)
    # a bandwidth longer than the series is clipped rather than crashing
    X = np.eye(6)
    cov, info = _hac_sandwich(X, np.ones(6), bandwidth=10 ** 6)
    assert info['bandwidth'] <= 5
    assert np.all(np.isfinite(cov))


def test_hac_reacts_to_correlation_in_the_expected_direction():
    """Positive autocorrelation must push the variance up, negative down."""
    n = 200
    rng = np.random.default_rng(7)
    X = _design(n)
    XtX_inv = np.linalg.inv(X.T @ X)

    def predicted_std(e):
        resid = e - X @ (XtX_inv @ (X.T @ e))
        cov, _ = _hac_sandwich(X, resid)
        return math.sqrt(cov[1, 1])

    # build errors with a prescribed AR(1) structure by filtering white noise
    white = rng.normal(size=n)
    pos = np.convolve(white, np.ones(7) / 7, mode='same')
    neg = white - np.convolve(white, np.ones(7) / 7, mode='same')
    # normalise so the comparison is about structure, not amplitude
    pos *= np.std(white) / np.std(pos)
    neg *= np.std(white) / np.std(neg)
    naive_like = predicted_std(white)
    assert predicted_std(pos) > naive_like
    assert predicted_std(neg) < naive_like


# ======================================================= profile integration
def _profile(seed, correlated, noise=0.5):
    pts = synthesise_pendant_drop(BO, RADIUS, APEX, n_per_branch=N_PTS,
                                  noise_px=0.0, seed=seed)
    rng = np.random.default_rng(seed)
    n = rng.normal(0.0, noise, pts.shape)
    if correlated:
        k = np.ones(5) / 5.0
        n = np.stack([np.convolve(n[i], k, mode='same') for i in range(2)])
        n *= math.sqrt(5.0)
    return pts + n


def test_covariance_is_invariant_to_the_order_of_the_profile_points():
    """The meridian reordering must make the result order-independent.

    A lag-based estimator applied to residuals in *array* order measures the
    wrong thing, because a profile's points are not stored in meridian order in
    general.  Since the residual set is identical, the covariance must not care
    how the caller happened to order the points.
    """
    pts = _profile(11, correlated=True)
    res = young_laplace_fit(pts)
    assert res.ok

    rng = np.random.default_rng(0)
    perm = rng.permutation(pts.shape[1])
    pts_shuffled = pts[:, perm]

    cov_a, info_a = parameter_covariance(pts, res, method='hac')
    cov_b, info_b = parameter_covariance(pts_shuffled, res, method='hac')

    ratio = info_b['hac_std'] / info_a['hac_std']
    assert 0.9 < ratio < 1.1, (
        f'HAC standard error changed by {ratio:.3f}x when the points were '
        f'reordered; the meridian ordering is not being applied')


def test_correlated_noise_gives_a_larger_hac_than_naive_error_bar():
    """The direction that matters: the naive bar is the one that is too small."""
    pts = _profile(5, correlated=True)
    res = young_laplace_fit(pts)
    assert res.ok
    _, info = parameter_covariance(pts, res, method='naive')
    assert info['inflation_vs_naive'] is not None
    assert info['hac_std'] > info['naive_std'], info
    assert 'hac' in info['note'], info['note']


def test_independent_noise_does_not_trigger_the_hac_recommendation():
    pts = _profile(5, correlated=False)
    res = young_laplace_fit(pts)
    assert res.ok
    _, info = parameter_covariance(pts, res, method='naive')
    # on i.i.d. noise the two estimators should be in the same ballpark
    assert 0.6 < info['inflation_vs_naive'] < 1.6, info


def test_strong_correlation_triggers_an_explicit_do_not_trust_this_note():
    """When neither estimator is adequate the code must say so, with numbers.

    Strongly autocorrelated residuals are exactly the case where a quietly
    too-small error bar does the most damage, so the function is required to
    report the measured recoveries and point at the bootstrap instead of
    returning a confident-looking number.
    """
    pts = _profile(9, correlated=True)
    # smooth the profile noise hard enough to force strong autocorrelation
    res = young_laplace_fit(pts)
    assert res.ok
    _, info = parameter_covariance(pts, res, method='hac')
    assert info['residual_autocorrelation'] is not None
    if info['residual_autocorrelation'] > 0.5:
        assert 'strongly autocorrelated' in info['note']
        assert 'bootstrap_parameters' in info['note']
        # the recoveries are quoted from the measured table, not invented
        assert '56%' in info['note'] and '27%' in info['note']


def test_default_method_is_hac_and_diagnostics_are_always_present():
    pts = _profile(3, correlated=True)
    res = young_laplace_fit(pts)
    cov, info = parameter_covariance(pts, res)
    assert info['method'] == 'hac'
    assert cov is not None
    for key in ('naive_std', 'hac_std', 'inflation_vs_naive', 'bandwidth',
                'dof', 'residual_std', 'residual_autocorrelation'):
        assert key in info, key


def test_an_unknown_method_is_rejected():
    pts = _profile(3, correlated=False)
    res = young_laplace_fit(pts)
    with np.testing.assert_raises(ValueError):
        parameter_covariance(pts, res, method='magic')


def test_a_failed_fit_yields_no_covariance():
    class _Bad:
        ok = False
    cov, info = parameter_covariance(np.zeros((2, 40)), _Bad())
    assert cov is None
    assert 'failed' in info['note']


if __name__ == '__main__':
    fns = [v for k, v in sorted(globals().items()) if k.startswith('test_')]
    bad = 0
    for fn in fns:
        try:
            fn()
            print(f'  PASS  {fn.__name__}')
        except AssertionError as e:
            bad += 1
            print(f'  FAIL  {fn.__name__}: {e}')
    print(f'{len(fns) - bad}/{len(fns)} passed')
    sys.exit(1 if bad else 0)
